### ISSUE TITLE
@supabase/ssr NextJs 14 middleware broke in 0.0.8

### ISSUE THREAD

**Issue by rcoopr** [supabase/auth-helpers#676]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

NextJs middleware (14.0.1) no longer works after upgrading from @supabase/ssr from 0.0.7 to 0.0.8

Specifically,  the `cookie.get` method ends up being called with undefined instead of `name`. I believe this may be related to the deletion of `cookieOptions.name` in the latest patch? 
```
unhandledRejection: TypeError: Cannot read properties of undefined (reading 'name')
    at RequestCookies.get
```

Code for middleware was taken directly from the docs. Downgrading to 0.0.7 fixes the issue.

```ts
// middleware.ts
import { type CookieOptions, createServerClient } from '@supabase/ssr'
import { type NextRequest, NextResponse } from 'next/server'

export async function middleware(request: NextRequest) {
  let response = NextResponse.next({
    request: {
      headers: request.headers,
    },
  })

  const supabase = createServerClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return request.cookies.get(name)?.value
        },
        remove(name: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value: '',
            ...options,
          })
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          })
          response.cookies.set({
            name,
            value: '',
            ...options,
          })
        },
        set(name: string, value: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value,
            ...options,
          })
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          })
          response.cookies.set({
            name,
            value,
            ...options,
          })
        },
      },
    },
  )

  await supabase.auth.getSession()

  return response
}
```

## System information

- OS: Windows
- Version of supabase-js: 2.38.4
- Version of Node.js: 18.16.0

**Comment by thisislvca** [comment]
+1 I'm having the same issue. Everything is updated. Strangely, the supabase example project works just fine... I'm confused as to why we have to do all the middleware cookie stuff ourselves... that only complicates things further.

Previously I could just refresh the user session by doing  
```typescript
const {
    data: { session },
  } = await supabase.auth.getSession();
  ```

But now the middleware client needs cookies and returns a response. Isn't that just plain out superfluous since the auth.getSession() automatically updates cookies?

I'm just confused, the ssr package seems a step backwards that just adds more complexity and potential breaking points...

**Comment by sldone** [comment]
The same issue while trying to exchange code for the session. 
Interesting thing is cookies set but with name like `undefined.0`

**Comment by sldone** [comment]
I found some workaround here.

We have to provide the name of the cookies.

Server client
```typescript
export const createClient = (cookieStore: ReturnType<typeof cookies>) => {
  return createServerClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookieOptions: {
        name: 'sb:token',
      },
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({name, value, ...options})
          } catch (error) {}
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({name, value: '', ...options})
          } catch (error) {}
        },
      },
    },
  )
}

```

Browser client
```typescript
export const createClient = () =>
  createBrowserClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {},
      cookieOptions: {
        name: 'sb:token',
      },
    },
  )

```

That's the only way I found to make it work at the moment.

**Comment by atanaskanchev** [comment]
+1 
```
[TypeError: Cannot read properties of undefined (reading 'name')]
TypeError: Cannot read properties of undefined (reading 'name')
    at RequestCookies.get (webpack-internal:///(middleware)/./node_modules/next/dist/compiled/@edge-runtime/cookies/index.js:205:70)
    at Object.get (webpack-internal:///(middleware)/./utils/supabase/middleware.ts:19:40)
    at eval (webpack-internal:///(middleware)/./node_modules/@supabase/ssr/dist/index.mjs:235:50)
    at combineChunks (webpack-internal:///(middleware)/./node_modules/@supabase/ssr/dist/index.mjs:59:25)
    at Object.getItem (webpack-internal:///(middleware)/./node_modules/@supabase/ssr/dist/index.mjs:233:49)
    at getItemAsync (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/lib/helpers.js:107:33)
    at SupabaseAuthClient.__loadSession (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:881:98)
    at SupabaseAuthClient._useSession (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:864:39)
    at SupabaseAuthClient._emitInitialSession (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:1362:27)
    at eval (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:1352:22)
```

**Comment by LHDi** [comment]
+1 `ssr` is a downgrade 🥲

**Comment by thisislvca** [comment]
> I found some workaround here.
> 
> 
> 
> We have to provide the name of the cookies.
> 
> 
> 
> Server client
> 
> ```typescript
> 
> export const createClient = (cookieStore: ReturnType<typeof cookies>) => {
> 
>   return createServerClient<Database>(
> 
>     process.env.NEXT_PUBLIC_SUPABASE_URL!,
> 
>     process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
> 
>     {
> 
>       cookieOptions: {
> 
>         name: 'sb:token',
> 
>       },
> 
>       cookies: {
> 
>         get(name: string) {
> 
>           return cookieStore.get(name)?.value
> 
>         },
> 
>         set(name: string, value: string, options: CookieOptions) {
> 
>           try {
> 
>             cookieStore.set({name, value, ...options})
> 
>           } catch (error) {}
> 
>         },
> 
>         remove(name: string, options: CookieOptions) {
> 
>           try {
> 
>             cookieStore.set({name, value: '', ...options})
> 
>           } catch (error) {}
> 
>         },
> 
>       },
> 
>     },
> 
>   )
> 
> }
> 
> 
> 
> ```

Another thing that I think isn't needed is getting the cookieStore straight from the import (without passing it as a prop every time). It was like this with the auth helpers...

**Comment by thisislvca** [comment]
> +1 in the `npx create-next-app -e with-supabase` template 
> 
> 
> 
> ```
> 
> [TypeError: Cannot read properties of undefined (reading 'name')]
> 
> TypeError: Cannot read properties of undefined (reading 'name')
> 
>     at RequestCookies.get (webpack-internal:///(middleware)/./node_modules/next/dist/compiled/@edge-runtime/cookies/index.js:205:70)
> 
>     at Object.get (webpack-internal:///(middleware)/./utils/supabase/middleware.ts:19:40)
> 
>     at eval (webpack-internal:///(middleware)/./node_modules/@supabase/ssr/dist/index.mjs:235:50)
> 
>     at combineChunks (webpack-internal:///(middleware)/./node_modules/@supabase/ssr/dist/index.mjs:59:25)
> 
>     at Object.getItem (webpack-internal:///(middleware)/./node_modules/@supabase/ssr/dist/index.mjs:233:49)
> 
>     at getItemAsync (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/lib/helpers.js:107:33)
> 
>     at SupabaseAuthClient.__loadSession (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:881:98)
> 
>     at SupabaseAuthClient._useSession (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:864:39)
> 
>     at SupabaseAuthClient._emitInitialSession (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:1362:27)
> 
>     at eval (webpack-internal:///(middleware)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:1352:22)
> 
> ```

Strange... with me the example works just fine lol

**Comment by LHDi** [comment]
@thisislvca try deploying it to Vercel edge?

**Comment by silentworks** [comment]
We've reverted the version with the broken code. We were trying to fix another issue relating to cookie name not setting and this created a break in the `0.0.8` release.

**Comment by RobinGiel** [comment]
@silentworks with 0.0.9  do we need to change or remove something in de server.ts for the example to work? 
` cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },`

**Comment by silentworks** [comment]
@RobinGiel I don't understand what you are asking here. The steps to use tha `ssr` package are in the docs here https://supabase.com/docs/guides/auth/server-side/creating-a-client

**Comment by DevRyuki** [comment]
I have also encountered the same issue.

I set up using the following commands:

```bash
npx supabase init
npx npx create-next-app@latest --typescript -e with-supabase
npx supabase start
```

However, I received the following error:

```plaintext
Error: Cannot read properties of undefined (reading 'name')
return cookieStore.get(name)?.value
```

**Comment by RobinGiel** [comment]
> @RobinGiel I don't understand what you are asking here. The steps to use the `ssr` package are in the docs here https://supabase.com/docs/guides/auth/server-side/creating-a-client

Yes following the docs and the example but I'm also getting errors the same as @DevRyuki is getting

**Comment by code-vagabond** [comment]
As pointed out in other issue, downgrading `@supabase/ssr` to `0.0.6` is a temporary fix

Upgrading to `0.0.9` get rid of `Cannot read properties of undefined (reading 'name')` issue but data is saved in an 'undefined' cookie key making it unaccessible to the authorization flow

**Comment by RobinGiel** [comment]
> As pointed out in the other issue, downgrading `@supabase/ssr` to `0.0.6` is a temporary fix.
> 
> Upgrading to `0.0.9` get rid of `Cannot read properties of undefined (reading 'name')` issue but data is saved in an 'undefined' cookie key making it inaccessible to the authorization flow.

I just downgrade to 0.0.6 and indeed no more issue. And after I updated back to 0.0.9 and had again no issues. Maybe it's an issue with the local node_modules

**Comment by DevRyuki** [comment]
> As pointed out in the other issue, downgrading `@supabase/ssr` to `0.0.6` is a temporary fix.
> 
> Upgrading to `0.0.9` get rid of `Cannot read properties of undefined (reading 'name')` issue but data is saved in an 'undefined' cookie key making it inaccessible to the authorization flow.



> > As pointed out in the other issue, downgrading `@supabase/ssr` to `0.0.6` is a temporary fix.
> > Upgrading to `0.0.9` get rid of `Cannot read properties of undefined (reading 'name')` issue but data is saved in an 'undefined' cookie key making it inaccessible to the authorization flow.
> 
> I just downgrade to 0.0.6 and indeed no more issue. And after I updated back to 0.0.9 and had again no issues. Maybe it's an issue with the local node_modules

Changing "@supabase/ssr": "latest" to "@supabase/ssr": "0.0.6" and running it did not cause any issues.

Afterwards, changing the version to "@supabase/ssr": "0.0.9" and running it also did not cause any issues.
Furthermore, changing it back to "@supabase/ssr": "latest" did not result in any problems.

SignIn and SignUp were both successful without any issues.

**Comment by code-vagabond** [comment]
Tested again and 0.0.9 worked fine, sorry for the confusion

**Comment by thisislvca** [comment]
I think we can close the issue 💪

**Comment by rossicodes** [comment]
I still get this issue, even when I downgrade to 0.0.6...anyone else?

**Comment by silentworks** [comment]
Thank you everyone for reporting back on the `0.0.9` release. I'm going to close this issue out as it seems to have been resolved in `0.0.9`.

**Comment by gokulkrishh** [comment]
Same issue is there in latest

```json
 "@supabase/ssr": "^0.1.0",
 "@supabase/supabase-js": "^2.39.3",
```  

```js
Error: Cannot find module '@supabase/ssr'
```

**Comment by thisislvca** [comment]
That doesn't sound like a supabase error, but more like a package manager error. Try to uninstall and reinstall the package :)

**Comment by silentworks** [comment]
@gokulkrishh as @thisislvca mentioned this is likely a package manager issue. You can see 0.1.0 was published to npm by the supabase team 2 days ago https://www.npmjs.com/package/@supabase/ssr.

**Comment by gokulkrishh** [comment]
@silentworks Yes, its an issue with the pkg manager. I found out the bug thats causing this issue. [Link to bug](https://github.com/vercel/next.js/issues/62037) i opened in NextJS.
